// <auto-generated />
namespace RS.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Corev10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corev10));
        
        string IMigrationMetadata.Id
        {
            get { return "201709060659058_Core-v.1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
